language: python

python:
  - "3.7"

install:
  - pip install flake8 pylint scapy tornado pytest
  - python setup.py install

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pylint --errors-only wifiphisher
  - py.test

notifications:
  email:
    on_success: never
    on_failure: always

addons:
    apt:
        packages:
          - libnl-3-dev
          - libnl-genl-3-dev
          - hostapd
          - dnsmasq
